---
title: "tb"
author: "Reetom Gangopadhyay"
date: "2024-07-15"
output: html_document
---



```{r}

data <- read.csv("ukr_adults_SIBS.csv")

head(data)

# summary(data)

```



```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)

#top10
top_outcomes <- data %>%
  count(Outcome, sort = TRUE) %>%
  head(10)

#plot top10
ggplot(top_outcomes, aes(x = Outcome, y = n)) +
  geom_bar(stat = "identity", fill = "blue", color = "black") +
  theme_minimal() +
  labs(title = "Top 10 Outcomes", x = "Outcome", y = "Count")

```

```{r,warning=FALSE}

library(dplyr)
library(lubridate)

data_clean <- data

```


```{r changefn}

# make a function for positive or yes to 1 and negative or 0 to no
change_fn <- function(col) {
  col[col == "Positive" | col == "Yes"] <- 1
  col[col == "Negative" | col == "No"] <- 0
  return(col)
}

```

```{r}

# fillna in the hiv_def as negative
data_clean$hiv_def[is.na(data_clean$hiv_def)] <- "Negative"

# swap positive to 1 and negative to 0
#data_clean$hiv_def[data_clean$hiv_def == "Positive"] <- 1
#data_clean$hiv_def[data_clean$hiv_def == "Negative"] <- 0

data_clean$hiv_def <- change_fn(data_clean$hiv_def)

# change has started to take art col name to "takes_art"
if ("Has.started.to.take.ART." %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(takes_art = Has.started.to.take.ART.)
}

# make NA values in takes_art to the date of the epoch convert col to date/time element with m/dd/yyyy format
# Replace NA values with a placeholder date
#data_clean$takes_art[is.na(data_clean$takes_art)] <- "1/1/1970"

# Parse dates, using a flexible date parsing function
data_clean$takes_art <- parse_date_time(data_clean$takes_art, orders = c("mdy", "dmy", "ymd"))

# Check for any parsing issues
#data_clean$takes_art[is.na(data_clean$takes_art)] <- as.Date("1970-01-01") # Replace any remaining NA with epoch date

# change col Cotrimoxazole.treatment to date/time element with m/dd/yyyy format
data_clean$Cotrimoxazole.treatment <- parse_date_time(data_clean$Cotrimoxazole.treatment, orders = c("mdy", "dmy", "ymd")
                                                      )

# change col Alcohol.abuse NA to "No" and then use chang_fn

data_clean$Alcohol.abuse[is.na(data_clean$Alcohol.abuse)] <- "No"
data_clean$Alcohol.abuse[data_clean$Alcohol.abuse == "-"] <- "No"

data_clean$Alcohol.abuse <- change_fn(data_clean$Alcohol.abuse)

# change col Injecting.drug.user NA to "No" and then use chang_fn

data_clean$Injecting.drug.user[is.na(data_clean$Injecting.drug.user)] <- "No"
data_clean$Injecting.drug.user[data_clean$Injecting.drug.user == "-"] <- "No"

data_clean$Injecting.drug.user <- change_fn(data_clean$Injecting.drug.user)





```


## MULTIPLE IMPUTATION FOR MISSING WEIGHTS. FIXED AGE AND WEIGHTS BEFORE MISSING TOO

```{r,warning=FALSE}

library(mice)
library(dplyr)
library(ggplot2)

clean_weights <- function(weight) {
  # Convert weights from pounds to kilograms if they are between 140 and 240
  weight <- ifelse(weight > 140 & weight < 240, weight / 2.20462, weight)
  
  # Add a decimal point for weights between 240 and 1000
  weight <- ifelse(weight >= 240 & weight <= 1000, weight / 10, weight)
  
  # Set weights higher than 1000 to NA
  weight <- ifelse(weight > 1000, NA, weight)
  
  return(weight)
}

correct_age <- function(age) {
  # Remove the leading '1' for ages greater than 100
  corrected_age <- ifelse(age > 100, age %% 100, age)
  return(corrected_age)
}


data_clean$Weight <- clean_weights(data_clean$Weight)
data_clean$Age <- correct_age(data_clean$Age)

# Create a new data frame for imputation
oldWeights <- data.frame(Age = data_clean$Age, Sex = data_clean$Sex, Weight = data_clean$Weight)

# Perform multiple imputation
imputedWeights <- mice(oldWeights, m = 5, method = "pmm", seed = 123)

# Extract the imputed weights
impute_weight <- complete(imputedWeights, action = "long", include = TRUE)
imputed_weight <- impute_weight[impute_weight$.imp == 1, ]

# Check weight order and add imputed weights to the original data
imputed_weight <- imputed_weight %>%
  arrange(.id)
data_clean$imputed_weight <- imputed_weight$Weight

# Check the density plot of the imputed weights
ggplot(data_clean, aes(x = imputed_weight)) +
  geom_density(fill = "blue", color = "black") +
  xlim(0, 200) +
  theme_minimal() +
  labs(title = "Density Plot of Imputed Weight", x = "Weight", y = "Density")

ggplot(data_clean, aes(x = Weight)) +
  geom_density(fill = "blue", color = "black") +
  xlim(0, 200) +
  theme_minimal() +
  labs(title = "Density Plot of Weight", x = "Weight", y = "Density")

mean_imputed_weight <- mean(data_clean$imputed_weight)
mean_weight <- mean(data_clean$Weight, na.rm = TRUE)

cat("Mean of Imputed Weight: ", mean_imputed_weight, "\n")
cat("Mean of Weight: ", mean_weight, "\n")



```

```{r,warning=FALSE}

library(dplyr)
library(lubridate)
library(tidyverse)
library(ggplot2)

# Function for making dataframe date time object
date_time <- function(col) {
  col <- parse_date_time(col, orders = c("mdy", "dmy", "ymd"))
  return(col)
}

#rename Treatment.start.date to start_date
if ("Treatment.start.date" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(start_date = Treatment.start.date)
}

data_clean$start_date <- date_time(data_clean$start_date)

if ("Treatment.end.date" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(end_date = Treatment.end.date)
}

data_clean$end_date <- date_time(data_clean$end_date)

# Make a new variable which gives elapsed time between treatment start date and end date and is NA for NA values

data_clean$elapsed_time <- as.numeric(difftime(data_clean$end_date, data_clean$start_date, units = "days"))

# generate distribution for sex
ggplot(data_clean, aes(x = Sex)) +
  geom_bar(fill = "blue") +
  labs(title = "Distribution of Sex", x = "Sex", y = "Frequency") +
  theme_minimal()

# change Localization to 1 for Pulmonary, 2 for Extra-pulmonary and 0 for Both

data_clean$Localization[data_clean$Localization == "Pulmonary"] <- 1
data_clean$Localization[data_clean$Localization == "Extra-pulmonary"] <- 2
data_clean$Localization[data_clean$Localization == "Both"] <- 0

ggplot(data_clean, aes(x = Localization)) +
  geom_bar(fill = "blue") +
  labs(title = "Distribution of Localization", x = "Localization", y = "Frequency") +
  theme_minimal()

```

```{r,warning=FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse)

if ("HIV.testing" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(hiv_testing = HIV.testing)
}

data_clean$hiv_testing <- date_time(data_clean$hiv_testing)

# change cavitation to 1 for Yes and 0 for No

data_clean$Cavitation <- change_fn(data_clean$Cavitation)

# change homeless and Unemployed and Healthcare.worker to No for "-" and NA

data_clean$Homeless[is.na(data_clean$Homeless)] <- "No"
data_clean$Homeless[data_clean$Homeless == "-"] <- "No"

data_clean$Homeless <- change_fn(data_clean$Homeless)

data_clean$Unemployed[is.na(data_clean$Unemployed)] <- "No"
data_clean$Unemployed[data_clean$Unemployed == "-"] <- "No"

data_clean$Unemployed <- change_fn(data_clean$Unemployed)

if ("Healthcare.worker" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(healthcare_worker = Healthcare.worker)
}

data_clean$healthcare_worker[is.na(data_clean$healthcare_worker)] <- "No"
data_clean$healthcare_worker[data_clean$healthcare_worker == "-"] <- "No"

data_clean$healthcare_worker <- change_fn(data_clean$healthcare_worker)

# sample date

if ("Sample.collection.date" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(sample_date = Sample.collection.date)
}

data_clean$sample_date <- date_time(data_clean$sample_date)

# prisoner 0 1

data_clean$Prisoner[is.na(data_clean$Prisoner)] <- "No"
data_clean$Prisoner[data_clean$Prisoner == "-"] <- "No"

data_clean$Prisoner <- change_fn(data_clean$Prisoner)

# fill NA in GeneXpert as Negative

data_clean$GeneXpert[is.na(data_clean$GeneXpert)] <- "Negative"

data_clean$GeneXpert <- change_fn(data_clean$GeneXpert)

# 0 1 for migrant_refugee

data_clean$migrant_refugee[is.na(data_clean$migrant_refugee)] <- "No"
data_clean$migrant_refugee <- change_fn(data_clean$migrant_refugee)

# change case.start and case.end to datetime

data_clean$case.start <- date_time(data_clean$case.start)

data_clean$case.end <- date_time(data_clean$case.end)


```


```{r}

library(dplyr)
library(ggplot2)
library(tidyverse)

# write a function that changes NA Vaues to Negative

change_fn1 <- function(col) {
  col[is.na(col)] <- "Negative"
  return(col)
}

# Use this function on col Culture.result.Bactec and rename it to Bactec

if ("Culture.result.Bactec" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(Bactec = Culture.result.Bactec)
}

data_clean$Bactec <- change_fn1(data_clean$Bactec)

# do the same for Culture.result.LowensteinJensen and rename it to LJ

if ("Culture.result.LowensteinJensen" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(LJ = Culture.result.LowensteinJensen)
}

data_clean$LJ <- change_fn1(data_clean$LJ)

# Make another variable "prev_treatment" for whether a person was previously treated (1) or Not (0) based on the variable new_prev

data_clean$prev_treatment <- ifelse(data_clean$new_prev == "Yes", 1, 0)


```


```{r DST ,warning=FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse)

# function DST_fn that changes NA values to 0, "Resistant" to 1 and "Sensitive" to 2 and Contaminated to 3

DST_fn <- function(col) {
  col[is.na(col)] <- 0
  col[col == "Resistant"] <- 1
  col[col == "Sensitive"] <- 2
  col[col == "Contaminated"] <- 3
  return(col)
}

if ("DST.result.R" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_R = DST.result.R)
}

data_clean$DST_R <- DST_fn(data_clean$DST_R)

if ("DST.result.E" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_E = DST.result.E)
}

data_clean$DST_E <- DST_fn(data_clean$DST_E)

if ("DST.result.Z" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Z = DST.result.Z)
}

data_clean$DST_Z <- DST_fn(data_clean$DST_Z)

if ("DST.result.S" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_S = DST.result.S)
}

data_clean$DST_S <- DST_fn(data_clean$DST_S)

if ("DST.result.H" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_H = DST.result.H)
}

data_clean$DST_H <- DST_fn(data_clean$DST_H)

# Am
if ("DST.result.Am" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Am = DST.result.Am)
}

data_clean$DST_Am <- DST_fn(data_clean$DST_Am)

# Cm

if ("DST.result.Cm" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Cm = DST.result.Cm)
}

data_clean$DST_Cm <- DST_fn(data_clean$DST_Cm)

# LFX and MFX

if ("DST.result.Lfx" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_LFX = DST.result.Lfx)
}

data_clean$DST_LFX <- DST_fn(data_clean$DST_LFX)

if ("DST.result.Mfx" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_MFX = DST.result.Mfx)
}

data_clean$DST_MFX <- DST_fn(data_clean$DST_MFX)

#PAS

if ("DST.result.PAS" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_PAS = DST.result.PAS)
}

data_clean$DST_PAS <- DST_fn(data_clean$DST_PAS)

# Km

if ("DST.result.Km" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Km = DST.result.Km)
}

data_clean$DST_Km <- DST_fn(data_clean$DST_Km)

# Ofx

if ("DST.result.Ofx" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Ofx = DST.result.Ofx)
}

data_clean$DST_Ofx <- DST_fn(data_clean$DST_Ofx)

# Et

if ("DST.result.Et" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Et = DST.result.Et)
}

data_clean$DST_Et <- DST_fn(data_clean$DST_Et)

# Gfx

if ("DST.result.Gfx" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Gfx = DST.result.Gfx)
}

data_clean$DST_Gfx <- DST_fn(data_clean$DST_Gfx)

# Lzd

if ("DST.result.Lzd" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Lzd = DST.result.Lzd)
}

data_clean$DST_Lzd <- DST_fn(data_clean$DST_Lzd)

# Cs

if ("DST.result.Cs" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Cs = DST.result.Cs)
}

data_clean$DST_Cs <- DST_fn(data_clean$DST_Cs)

# Cfx

if ("DST.result.Cfx" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Cfx = DST.result.Cfx)
}

data_clean$DST_Cfx <- DST_fn(data_clean$DST_Cfx)

# Sfx

if ("DST.result.Sfx" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Sfx = DST.result.Sfx)
}

data_clean$DST_Sfx <- DST_fn(data_clean$DST_Sfx)

# Pa

if ("DST.result.Pa" %in% colnames(data_clean)) {
  data_clean <- data_clean %>%
    rename(DST_Pa = DST.result.Pa)
}

data_clean$DST_Pa <- DST_fn(data_clean$DST_Pa)





```


```{r}

# save data_clean to csv clean_ukr.csv

write.csv(data_clean, "clean_ukr.csv")

test <- read.csv("clean_ukr.csv")

```



