---
title: "TB_analysis"
author: "Reetom Gangopadhyay"
date: "2024-07-31"
output: pdf_document
---

```{r,warning=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)

data <- read.csv("clean_ukr.csv")

if ("X" %in% colnames(data)) {
  data <- data %>% select(-X)
} # not necessary but for cleanliness 

head(data)
str(data)

```

```{r}

library(glmnet)
library(caret)

#### RUN ONCE MAX

data$hiv <- ifelse(is.na(data$takes_art), 0, 1)

data$Cot <- ifelse(is.na(data$Cotrimoxazole.treatment), 0, 1)


data$new_prev[is.na(data$new_prev)] <- "New"
data$prev_treatment <- ifelse(data$new_prev == "Previously treated", 1, 0)






```


```{r}
# str(data)

data <- data %>%
  mutate(
    final_outcome_group = as.factor(final_outcome_group),
    Sex = as.factor(Sex),
    Region = as.factor(Region),
    imputed_weight = as.numeric(imputed_weight),
    elapsed_time = as.numeric(elapsed_time),
    Age = as.numeric(Age),
    DST_R = as.factor(DST_R),
    
    Localization = as.factor(Localization),
    hiv_def = as.factor(hiv_def),
    hiv = as.factor(hiv),
    Cot = as.factor(Cot),
    Alcohol.abuse = as.factor(Alcohol.abuse),
    Injecting.drug.user = as.factor(Injecting.drug.user),
    Homeless = as.factor(Homeless),
    Unemployed = as.factor(Unemployed),
    healthcare_worker = as.factor(healthcare_worker),
    Prisoner = as.factor(Prisoner),
    migrant_refugee = as.factor(migrant_refugee),
    prev_treatment = as.factor(prev_treatment),
    
    Bactec = as.factor(Bactec),
    LJ = as.factor(LJ),
    GeneXpert = as.factor(GeneXpert),
    DST_E = as.factor(DST_E),
    DST_Z = as.factor(DST_Z),
    DST_S = as.factor(DST_S),
    DST_H = as.factor(DST_H),
    DST_Am = as.factor(DST_Am),
    DST_Cm = as.factor(DST_Cm),
    DST_LFX = as.factor(DST_LFX),
    DST_MFX = as.factor(DST_MFX),
    DST_PAS = as.factor(DST_PAS),
    DST_Km = as.factor(DST_Km),
    DST_Ofx = as.factor(DST_Ofx),
    DST_Et = as.factor(DST_Et),
    DST_Lzd = as.factor(DST_Lzd),
    DST_Cs = as.factor(DST_Cs),
  )

# Set the response variable to 'dropout' if 'Treatment discontinuation' in 'final_outcome_group'
data$dropout <- ifelse(data$final_outcome_group == "Treatment discontinuation", 1, 0)

# Confirm creation of 'dropout' variable
table(data$dropout) ## correct///

```


```{r}
#library(glmnet)
#library(caret)

# Define the response variable (Y) and predictor variables (X)
Y <- data$dropout 
X <- model.matrix(dropout ~ Sex + Region + imputed_weight + Age +
                  DST_R + Localization + hiv_def + hiv + Cot + Alcohol.abuse + Injecting.drug.user +
                  Homeless + Unemployed + healthcare_worker + Prisoner + migrant_refugee + prev_treatment +
                  Bactec + LJ + GeneXpert + DST_E + DST_Z + DST_S + DST_H + DST_Am + DST_Cm +
                  DST_LFX + DST_MFX + DST_PAS + DST_Km + DST_Ofx + DST_Et + DST_Lzd +
                  DST_Cs, data = data)#[,-1]  # to exclude intercept column

#X <- model.matrix(dropout ~ imputed_weight + Age + Sex + hiv + Localization + Region , data = data)#[,-1]  # to exclude intercept column


#X <- model.matrix(dropout ~ Sex + Region + imputed_weight + Age +
 #                 DST_R + Localization + hiv_def + hiv + Cot + Alcohol.abuse + Injecting.drug.user +
  #                Homeless + Unemployed + healthcare_worker + Prisoner + migrant_refugee, data = data) 

set.seed(123)
cv_lasso <- cv.glmnet(X, Y, family = "binomial", alpha = 1)

# Extract the best lambda
best_lambda <- cv_lasso$lambda.min

# Fit the final LASSO model with the best lambda
lasso_model <- glmnet(X, Y, family = "binomial", alpha = 1, lambda = best_lambda)

# Coefficients of the final model
lasso_coef <- coef(lasso_model)
print(lasso_coef)

# Visualize the cross-validation results
plot(cv_lasso)

# check number of rows of variable in X
nrow(X)
```


```{r}
library(ggplot2)

# Data: Variables and their coefficients
variables <- c("SexMale", "RegionChernihiv", "RegionChernivtsi", "RegionDnipropetrovsk", 
               "RegionDonetsk", "RegionIvano-Frankivsk", "RegionKharkiv", "RegionKherson", 
               "RegionKhmelnitsky", "RegionKievskaya", "RegionKirovograd", "RegionKyiv.City", 
               "RegionLugansk", "RegionLviv", "RegionNikolaev", "RegionOdessa", "RegionPoltava", 
               "RegionRivne", "RegionSumy", "RegionTernopil", "RegionTest", 
               "RegionTranscarpathian", "RegionVinnitsa", "RegionVolyn", 
               "RegionYanovsky.Institute", "RegionZaporozhye", "RegionZhytomyr", 
               "imputed_weight", "Age", "DST_R1", "DST_R2", "DST_R3", "Localization1", 
               "Localization2", "hiv_def1", "hiv_defUnknown", "hiv1", "Cot1", "Alcohol.abuse1", 
               "Injecting.drug.user1", "Homeless1", "Unemployed1", "healthcare_worker1", 
               "Prisoner1", "migrant_refugee1", "prev_treatment1", "Bactec++", 
               "Bactec+++", "BactecCulture.at.work", "BactecNegative", "BactecOvergrown", 
               "BactecPositive", "LJ++", "LJ+++", "LJCulture.at.work", "LJNegative", 
               "LJOvergrown", "LJPositive", "GeneXpert1", "DST_E1", "DST_E2", "DST_E3", 
               "DST_Z1", "DST_Z2", "DST_Z3", "DST_S1", "DST_S2", "DST_S3", "DST_H1", "DST_H2", 
               "DST_H3", "DST_Am1", "DST_Am2", "DST_Am3", "DST_Cm1", "DST_Cm2", "DST_Cm3", 
               "DST_LFX1", "DST_LFX2", "DST_LFX3", "DST_MFX1", "DST_MFX2", "DST_MFX3", 
               "DST_PAS1", "DST_PAS2", "DST_PAS3", "DST_Km1", "DST_Km2", "DST_Km3", 
               "DST_Ofx1", "DST_Ofx2", "DST_Ofx3", "DST_Et1", "DST_Et2", "DST_Et3", 
               "DST_Lzd1", "DST_Lzd2", "DST_Lzd3", "DST_Cs1", "DST_Cs2", "DST_Cs3")

coefficients <- c(0.351697894, 0.106650007, -0.013731107, 0.285392375, 0.049118274, 
                  0.144977510, 0.135062163, NA, -0.261594812, -0.014462811, -0.082027650, 
                  -0.053233680, 0.420157172, 0.039570567, -0.317895969, 0.262469062, 
                  -0.190017330, -0.899950883, -0.410905399, 0.033478896, -0.637504415, 
                  0.536330720, NA, 0.046957345, -0.295738998, 0.297372145, -0.122727215, 
                  -0.006787342, -0.008295576, 0.237384343, -0.132642686, -0.349166326, 
                  0.148300384, 0.007178760, -0.066980367, 0.315850537, -0.080231309, 
                  0.025859433, 0.291017825, 0.064314498, 0.999478318, 0.257696255, 
                  -1.430506283, 0.495007805, 0.378466556, 0.099693839, 0.219124059, 
                  -0.207184703, -0.737445677, -0.006935377, -0.240456459, -0.040599683, 
                  -0.041688163, 0.008670555, -0.225356789, 0.009078344, -0.141449104, 
                  0.016567474, -0.023998702, -0.075194550, NA, -1.214283468, -0.139525133, 
                  NA, 0.351227798, 0.043748060, 0.041188569, -0.338502432, 0.435797353, 
                  -0.038491102, 0.244660297, 0.135941266, 0.211822697, NA, -0.004392885, 
                  -0.003972153, NA, -0.061430186, -0.013817012, 2.189122281, -0.233981513, 
                  -0.143195895, -3.242326954, 0.119945215, 0.018262854, -3.266525503, 
                  -0.220318952, -0.182729738, 0.605282079, -0.193857059, 0.170199959, 
                  3.441514094, -0.102548524, NA, NA, -1.104955138, -0.744072176, 1.392621314, 
                  NA, 0.075462202, -0.052817734)

df <- data.frame(Variable = variables, Coefficient = coefficients)
df <- na.omit(df)

ggplot(df, aes(x = reorder(Variable, Coefficient), y = Coefficient)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  coord_flip() +
  labs(title = "Lasso Selected Variables and Their Coefficients",
       x = "Variable",
       y = "Coefficient") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 4))


```



## No need to run
```{r testing parameters}

# Check the number of levels for each factor variable
factor_vars <- c("final_outcome_group", "Sex", "Region", "DST_R", "Localization", "hiv_def", 
                 "hiv", "Cot", "Alcohol.abuse", "Injecting.drug.user", "Homeless", 
                 "Unemployed", "healthcare_worker", "Prisoner", "migrant_refugee", 
                 "prev_treatment", "Bactec", "LJ", "GeneXpert", "DST_E", "DST_Z", "DST_S", 
                 "DST_H", "DST_Am", "DST_Cm", "DST_LFX", "DST_MFX", "DST_PAS", "DST_Km", 
                 "DST_Ofx", "DST_Et", "DST_Lzd", "DST_Cs")

for (var in factor_vars) {
  levels_count <- length(unique(data[[var]]))
 # if (levels_count == 1) {
  cat(var, "has", levels_count, "levels.\n")
  #}
}


```

## CART Analysis
```{r}

###  tbd. ###

```




